### ISSUE TITLE
error with greml using different kinships

### ISSUE THREAD

**Issue by sofifagro** [psoerensen/qgg#11]
Dear Dr. Sørensen,

I am experiencing an error when using greml function. Specifically, I am getting the following: 

`Error in chol.default(V) :

  the leading minor of order 1 is not positive definite`

I have calculated G following the two approaches from the qgg page, using rrBLUP and using LDAK, but all gives me the same error in `chol(V)`. Would you please guide me how to proceed? 

Kind regards,
Sofi

**Comment by psoerensen** [comment]
Dear Sofi,
I probably need slightly more information about your data before I can
determine what the problem is. It may be something related to your
phenotype (y) or your design matrix (X) for the fixed effects. Are there
any missing values, NAs something like that? Could you send me a few more
lines from the script you are using to run your analyses?
Kind regards
Peter

**Comment by sofifagro** [comment]
Dear Peter, 

Thank you very much for your reply. I took out the individuals with NAs from the phenotypic data and I could get the code running and initial results. I am closing the issue :) 

Kind regards,
Sofi

**Comment by psoerensen** [comment]
Dear Sofi,
glad to hear you got the code running!
Kind regards
Peter
