### ISSUE TITLE
Fitting baseline model without GRM

### ISSUE THREAD

**Issue by aneumann-science** [psoerensen/qgg#8]
Hi all,

I was wondering whether it is possible to run the greml function without providing a genetic relatedness matrix (GRM) or with an identity matrix only. Running without the GRM argument gives the error "object 'fit' not found" and providing an identity matrix leaves "Error in solve.default(ai) : 
  Lapack routine dgesv: system is exactly singular: U[2,2] = 0".

The motivation behind the questions is, that when I run the full model with cross-validation, the resulting R2 also reflects variance explained by both the GRM and the covariates. So to determine the R2 by the GRM beyond the covariates, I would like to fit a baseline model without a GRM and substract the R2 of the baseline model from the full model.

**Comment by PDRohde** [comment]
Hi aneumann-science,

Thanks for your question- sorry for the late reply. 

I guess the reason why you cannot run the model with an identity matrix is that in that case the covariance structure of both  random effects will be identical; y=Xb+Zg+e, thus the covariance of g and e is identical which is not possible because you cannot partition variance between two equal matrices.  If you have repeated measures then your identity matrix is an identity block matrix which would be OK. 

You could instead adjust your phenotype prior to the analysis so your model would be y=Zg+e. 

Cheers
Palle
